## Pre-commit setup

ci:
  autofix_commit_msg: |
    style: auto fixes from pre-commit hooks
repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: Running black in all files.

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        name: Running ruff in all files.

  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.17.0
    hooks:
      - id: slotscheck
        name: Running slotscheck in all files.
        exclude: "^(?!mafic/)"
        additional_dependencies: [nextcord, aiohttp]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        name: Check if python files are valid syntax for the ast parser
      - id: check-case-conflict
        name: Check for case conflict on file names for case insensitive systems.
      - id: check-merge-conflict
        name: Check for merge conflict syntax.
      - id: check-toml
        name: Check TOML files for valid syntax.
      - id: check-yaml
        name: Check YAML files for valid syntax.
      - id: debug-statements
        name: Check for debug statements.
      - id: end-of-file-fixer
        name: Check for only one newline character at EOL.
        exclude: "^(test_bot/logs/)"
      - id: trailing-whitespace
        name: Check for trailing whitespace.
        args: [--markdown-linebreak-ext=md]
