version: "3"

services:
  bot:
    restart: on-failure:5
    depends_on:
      - lavalink
    build: .
    volumes:
      - ./logs:/bot/logs
      - ../mafic:/bot/mafic
    environment:
      TOKEN: $TOKEN
      GW_PROXY: ws://localhost:7878
      LAVALINK_FILE: lavalink/multi-nodes.json
    network_mode: host
  lavalink:
    image: ghcr.io/freyacodes/lavalink:v4
    volumes:
      - ./logs/lava:/opt/Lavalink/logs
    deploy:
      replicas: 8
    ports:
      - "6962-6969:6969"
    environment:
      JDK_JAVA_OPTIONS: -Xmx2G
      SERVER_PORT: 6969
      SERVER_ADDRESS: 0.0.0.0
      LAVALINK_SERVER_PASSWORD: haha
      LOGGING_FILE_PATH: ./logs/
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_LAVALINK: INFO
      LOGGING_REQUEST_ENABLED: true
      LOGGING_LOGBACK_ROLLINGPOLICY_MAXFILESIZE: 100MB
      LOGGING_LOGBACK_ROLLINGPOLICY_MAXHISTORY: 30
  gateway-proxy:
    image: gelbpunkt/gateway-proxy:x86-64
    volumes:
      - ./gateway-proxy/noshard.config.json:/config.json
    environment:
      TOKEN: $TOKEN
    ports:
      - "7878:7878"
